[project]
name = "hyptorch"
version = "0.1.0"
description = "Suite of hyperbolic neural networks in PyTorch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.15.2",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]


[tool.ruff]
line-length = 110
