[project]
name = "hyptorch"
dynamic = ["version"]
description = "Suite of hyperbolic neural networks in PyTorch"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
keywords = [
    "pytorch",
    "deep-learning",
    "hyperbolic",
    "neural-networks",
    "machine-learning",
]
dependencies = ["torch>=2.7.0", "torchvision>=0.22.0"]

[project.urls]
"Homepage" = "https://github.com/Iarrova/hyptorch"
"Source Code" = "https://github.com/Iarrova/hyptorch"
"Documentation" = "https://hyptorch.readthedocs.io/en/latest/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "hyptorch.__version__" }

[tool.ruff]
line-length = 110

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "SIM"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["hyptorch"]

[dependency-groups]
dev = ["pyright>=1.1.400", "pytest>=8.3.5"]

[project.optional-dependencies]
dev = ["pyright>=1.1.400", "pytest>=8.3.5"]
docs = [
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.7",
    "sphinx>=8.1.3",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.0.2",
]
examples = [
    "lightning>=2.5.5",
    "marimo>=0.15.2",
    "matplotlib>=3.10.6",
    "rich>=14.1.0",
]
